export const UPDATE_TASKS = 'UPDATE_TASKS';
export const ADD_TASK = 'ADD_TASK';

export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const ADD_CONTACTS = 'ADD_CONTACTS';

export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

export const UPDATE_EVENTS = 'UPDATE_EVENTS';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';

export const UPDATE_CURRENT_CATEGORY = 'UPDATE_MESSAGE';

export const UPDATE_ACCOUNT_NAME = 'UPDATE_ACCOUNT_NAME';
export const UPDATE_ACCOUNT_STATUS = 'UPDATE_ACCOUNT_STATUS';
